import "@repo/ui/styles.css";
import clsx from "clsx";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import MainLayout from "./(components)/MainLayout";
import "./globals.css";
import { ThemeProvider } from "./providers/ThemeProviders";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <ThemeProvider>
    <html lang="en">
      <body className={clsx(inter.className, "text-foreground bg-background")}>
        <MainLayout>{children}</MainLayout>
      </body>
    </html>
    </ThemeProvider>
  );
}
